/** Every TanStack Query key in one place (docs/PLAN.md §9.4). */
export const qk = {
  session: () => ["session"] as const,
  members: () => ["members"] as const,
  settings: () => ["settings"] as const,
  devices: () => ["devices"] as const,
  diagnostics: () => ["diagnostics"] as const,
  backups: () => ["backups"] as const,
  activeStore: () => ["stores", "active"] as const,
  dishes: () => ["dishes"] as const,
  dishList: (role: string, archived: boolean) => ["dishes", "list", role, archived] as const,
  dish: (id: string) => ["dishes", "one", id] as const,
  items: () => ["items"] as const,
  picker: (itemId: string) => ["items", "picker", itemId] as const,
  productSearch: (term: string) => ["products", term] as const,
  usualSides: (dishId: string) => ["dishes", "usual-sides", dishId] as const,
  plan: () => ["plan"] as const,
  alternatives: (itemId: string) => ["alternatives", itemId] as const,
  sections: () => ["stores", "sections"] as const,
  trips: () => ["trips"] as const,
  tripHistory: (before: string | null) => ["trips", "history", before] as const,
  trip: (id: string) => ["trips", "detail", id] as const,
};
