/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backups */
        get: operations["backups_api_admin_backups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/backups/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Backup */
        post: operations["run_backup_api_admin_backups_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/backups/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Backup */
        get: operations["download_backup_api_admin_backups__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostics */
        get: operations["diagnostics_api_admin_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_auth_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/devices/sign-out-others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Out Others */
        post: operations["sign_out_others_api_auth_devices_sign_out_others_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sign Out Device */
        delete: operations["sign_out_device_api_auth_devices__device_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/member": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Choose Member */
        put: operations["choose_member_api_auth_member_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dishes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dishes */
        get: operations["list_dishes_api_dishes_get"];
        put?: never;
        /** Create Dish */
        post: operations["create_dish_api_dishes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dishes/{dish_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dish */
        get: operations["get_dish_api_dishes__dish_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Dish */
        patch: operations["update_dish_api_dishes__dish_id__patch"];
        trace?: never;
    };
    "/api/dishes/{dish_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Dish */
        post: operations["archive_dish_api_dishes__dish_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dishes/{dish_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate Dish */
        post: operations["duplicate_dish_api_dishes__dish_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dishes/{dish_id}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace Lines */
        put: operations["replace_lines_api_dishes__dish_id__lines_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dishes/{dish_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Dish */
        post: operations["restore_dish_api_dishes__dish_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_items_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_api_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_items__item_id__patch"];
        trace?: never;
    };
    "/api/items/{item_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Item */
        post: operations["archive_item_api_items__item_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/picker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Amount Picker */
        get: operations["amount_picker_api_items__item_id__picker_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Amount */
        post: operations["preview_amount_api_items__item_id__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Item */
        post: operations["restore_item_api_items__item_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kroger/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Products
         * @description Search terms are never stored or logged (ADR 0016).
         */
        get: operations["search_products_api_kroger_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_members_get"];
        put?: never;
        /** Create Member */
        post: operations["create_member_api_members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Member */
        patch: operations["update_member_api_members__member_id__patch"];
        trace?: never;
    };
    "/api/members/{member_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Member */
        post: operations["archive_member_api_members__member_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{member_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Member */
        post: operations["restore_member_api_members__member_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Photo
         * @description The raw image is the request body (JPEG, PNG, WebP…), up to 15 MB.
         */
        post: operations["upload_photo_api_photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Photo */
        get: operations["get_photo_api_photos__photo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{photo_id}/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thumb */
        get: operations["get_thumb_api_photos__photo_id__thumb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/stores/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Store */
        get: operations["get_active_store_api_stores_active_get"];
        /** Choose Store */
        put: operations["choose_store_api_stores_active_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Stores */
        get: operations["search_stores_api_stores_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveStoreOut */
        ActiveStoreOut: {
            store: components["schemas"]["StoreOut"] | null;
        };
        /** AmountIn */
        AmountIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "packages" | "measure" | "count";
            /** Unit */
            unit?: string | null;
            /** Value */
            value: string;
        };
        /** AmountOut */
        AmountOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "packages" | "measure" | "count";
            /** Text */
            text: string;
            /** Unit */
            unit: string | null;
            /** Value */
            value: string;
        };
        /** BackupFileOut */
        BackupFileOut: {
            /** Bytes */
            bytes: number;
            /** Name */
            name: string;
        };
        /** BackupRunOut */
        BackupRunOut: {
            /** Bytes */
            bytes: number;
            /** File */
            file: string;
            /** Seconds */
            seconds: number;
        };
        /** BackupStatusOut */
        BackupStatusOut: {
            /** Directory */
            directory: string;
            /** Files */
            files: components["schemas"]["BackupFileOut"][];
            /** Last Error */
            last_error: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Retention */
            retention: string;
            /** Schedule */
            schedule: string;
            /** Stale */
            stale: boolean;
        };
        /** ChooseStore */
        ChooseStore: {
            /** Location Id */
            location_id: string;
        };
        /** ClientInfo */
        ClientInfo: {
            /** Resolved Ip */
            resolved_ip: string | null;
            /** Scheme */
            scheme: string;
            /** Trusted Proxies Configured */
            trusted_proxies_configured: boolean;
            /** X Forwarded For */
            x_forwarded_for: string | null;
            /** X Forwarded Proto */
            x_forwarded_proto: string | null;
        };
        /**
         * CostOut
         * @description What the dish's own amounts cost at today's prices, as an estimate.
         */
        CostOut: {
            /** About Dollars */
            about_dollars: number | null;
            /** Cents */
            cents: number | null;
            /** Unpriced */
            unpriced: number;
        };
        /** DeviceOut */
        DeviceOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Is Current */
            is_current: boolean;
            /** Label */
            label: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Member Name */
            member_name: string | null;
        };
        /** DiagnosticsOut */
        DiagnosticsOut: {
            backups: components["schemas"]["BackupStatusOut"];
            client: components["schemas"]["ClientInfo"];
            /** Kroger Mode */
            kroger_mode: string;
            live_updates: components["schemas"]["LiveUpdatesInfo"];
            /** Revision */
            revision: string;
            /** Schema Revision */
            schema_revision: string | null;
            /** Version */
            version: string;
        };
        /** DishCard */
        DishCard: {
            /** Archived */
            archived: boolean;
            cost: components["schemas"]["CostOut"];
            /** Favorite */
            favorite: boolean;
            /** Id */
            id: string;
            /** Item Images */
            item_images: string[];
            /** Name */
            name: string;
            /** Occasions */
            occasions: ("breakfast" | "lunch" | "dinner" | "snack")[];
            /** Photo Url */
            photo_url: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "main" | "side";
        };
        /** DishCreate */
        DishCreate: {
            /**
             * Favorite
             * @default false
             */
            favorite: boolean;
            /** Lines */
            lines?: components["schemas"]["LineIn"][];
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Occasions */
            occasions?: ("breakfast" | "lunch" | "dinner" | "snack")[];
            /** Photo Id */
            photo_id?: string | null;
            /** Recipe Url */
            recipe_url?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "main" | "side";
            /** Servings */
            servings?: number | null;
        };
        /** DishLineOut */
        DishLineOut: {
            amount: components["schemas"]["AmountOut"];
            /** Check Amount */
            check_amount: string | null;
            /** Cost Cents */
            cost_cents: number | null;
            /** Id */
            id: string;
            item: components["schemas"]["ItemOut"];
            /** Share Text */
            share_text: string | null;
        };
        /** DishOut */
        DishOut: {
            /** Archived */
            archived: boolean;
            cost: components["schemas"]["CostOut"];
            /** Favorite */
            favorite: boolean;
            /** Id */
            id: string;
            /** Lines */
            lines: components["schemas"]["DishLineOut"][];
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            /** Occasions */
            occasions: ("breakfast" | "lunch" | "dinner" | "snack")[];
            /** Photo Id */
            photo_id: string | null;
            /** Photo Url */
            photo_url: string | null;
            /** Recipe Url */
            recipe_url: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "main" | "side";
            /** Servings */
            servings: number | null;
        };
        /**
         * DishUpdate
         * @description Only the fields sent change; send null to clear servings, notes, the link or the photo.
         */
        DishUpdate: {
            /** Favorite */
            favorite?: boolean | null;
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            /** Occasions */
            occasions?: ("breakfast" | "lunch" | "dinner" | "snack")[] | null;
            /** Photo Id */
            photo_id?: string | null;
            /** Recipe Url */
            recipe_url?: string | null;
            /** Role */
            role?: ("main" | "side") | null;
            /** Servings */
            servings?: number | null;
        };
        /** EachWeightOut */
        EachWeightOut: {
            /** Prefill */
            prefill: string | null;
            /** Presets */
            presets: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** ItemCreate */
        ItemCreate: {
            /** Name */
            name: string;
            /** Product Id */
            product_id?: string | null;
        };
        /** ItemOut */
        ItemOut: {
            /** Archived */
            archived: boolean;
            /** Each Weight Lb */
            each_weight_lb: string | null;
            /** Id */
            id: string;
            /** Image Url */
            image_url: string | null;
            /** Is Staple */
            is_staple: boolean;
            /** Name */
            name: string;
            /** Product Id */
            product_id: string | null;
            /**
             * Size Source
             * @enum {string}
             */
            size_source: "parsed" | "household";
            /** Size Text */
            size_text: string | null;
            /** Sold By */
            sold_by: ("unit" | "weight") | null;
        };
        /**
         * ItemUpdate
         * @description Only the fields sent change. `product_id: null` unlinks; `size_text: null` undoes a fix.
         */
        ItemUpdate: {
            /** Each Weight Lb */
            each_weight_lb?: string | null;
            /** Is Staple */
            is_staple?: boolean | null;
            /** Name */
            name?: string | null;
            /** Product Id */
            product_id?: string | null;
            /** Size Text */
            size_text?: string | null;
        };
        /** KindOptionOut */
        KindOptionOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "packages" | "measure" | "count";
            /** Presets */
            presets: components["schemas"]["AmountOut"][];
            /** Step */
            step: string | null;
            /** Units */
            units: string[];
        };
        /** LineIn */
        LineIn: {
            amount: components["schemas"]["AmountIn"];
            /** Item Id */
            item_id: string;
        };
        /** LinesIn */
        LinesIn: {
            /** Lines */
            lines: components["schemas"]["LineIn"][];
        };
        /** LiveUpdatesInfo */
        LiveUpdatesInfo: {
            /** Connections */
            connections: number;
            /** Epoch */
            epoch: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Password */
            password: string;
        };
        /** MemberChoice */
        MemberChoice: {
            /** Member Id */
            member_id: string | null;
        };
        /** MemberCreate */
        MemberCreate: {
            /** Name */
            name: string;
        };
        /** MemberOut */
        MemberOut: {
            /** Id */
            id: string;
            /**
             * Marker Color
             * @enum {string}
             */
            marker_color: "basil" | "tomato" | "carrot" | "eggplant" | "beet" | "olive" | "cocoa" | "plum";
            /** Name */
            name: string;
        };
        /** MemberUpdate */
        MemberUpdate: {
            /** Marker Color */
            marker_color?: ("basil" | "tomato" | "carrot" | "eggplant" | "beet" | "olive" | "cocoa" | "plum") | null;
            /** Name */
            name?: string | null;
        };
        /** PhotoOut */
        PhotoOut: {
            /** Height */
            height: number;
            /** Id */
            id: string;
            /** Width */
            width: number;
        };
        /**
         * PickerOut
         * @description Everything the amount picker needs for one item (docs/UX.md §4.10).
         */
        PickerOut: {
            each_weight: components["schemas"]["EachWeightOut"] | null;
            /** Fix Size */
            fix_size: boolean;
            item: components["schemas"]["ItemOut"];
            /** Kinds */
            kinds: components["schemas"]["KindOptionOut"][];
            product: components["schemas"]["ProductResult"] | null;
        };
        /** PreviewIn */
        PreviewIn: {
            amount: components["schemas"]["AmountIn"];
        };
        /** PreviewOut */
        PreviewOut: {
            amount: components["schemas"]["AmountOut"] | null;
            /** Cost Cents */
            cost_cents: number | null;
            /** Message */
            message: string | null;
            /** Share Text */
            share_text: string | null;
            /** Valid */
            valid: boolean;
        };
        /** PriceOut */
        PriceOut: {
            /** Per Pound */
            per_pound: boolean;
            /** Regular Cents */
            regular_cents: number;
            /** Sale Cents */
            sale_cents: number | null;
            /** Sale Ends */
            sale_ends: string | null;
        };
        /**
         * ProductResult
         * @description A Kroger product, shown exactly as Kroger describes it. `product_id` links; never shown.
         */
        ProductResult: {
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "low" | "out" | "not_sold";
            /** Brand */
            brand: string | null;
            /** Description */
            description: string;
            /** Image Url */
            image_url: string | null;
            price: components["schemas"]["PriceOut"] | null;
            /** Product Id */
            product_id: string;
            /** Size */
            size: string | null;
            /**
             * Sold By
             * @enum {string}
             */
            sold_by: "unit" | "weight";
        };
        /** SessionOut */
        SessionOut: {
            /** Device Id */
            device_id: string;
            /** Household Name */
            household_name: string;
            member: components["schemas"]["MemberOut"] | null;
            /** Members */
            members: components["schemas"]["MemberOut"][];
        };
        /** SettingsOut */
        SettingsOut: {
            /** Household Name */
            household_name: string;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Household Name */
            household_name?: string | null;
        };
        /**
         * StoreOption
         * @description A store found near a ZIP code. `location_id` picks it; the screen never shows it.
         */
        StoreOption: {
            /** Address Lines */
            address_lines: string[];
            /** Location Id */
            location_id: string;
            /** Name */
            name: string;
        };
        /** StoreOut */
        StoreOut: {
            /** Address Lines */
            address_lines: string[];
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionOut */
        VersionOut: {
            /** Created */
            created: string | null;
            /** Revision */
            revision: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    backups_api_admin_backups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupStatusOut"];
                };
            };
        };
    };
    run_backup_api_admin_backups_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupRunOut"];
                };
            };
        };
    };
    download_backup_api_admin_backups__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnostics_api_admin_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsOut"];
                };
            };
        };
    };
    list_devices_api_auth_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"][];
                };
            };
        };
    };
    sign_out_others_api_auth_devices_sign_out_others_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sign_out_device_api_auth_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    choose_member_api_auth_member_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberChoice"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    list_dishes_api_dishes_get: {
        parameters: {
            query?: {
                role?: ("main" | "side") | null;
                q?: string | null;
                occasion?: ("breakfast" | "lunch" | "dinner" | "snack") | null;
                favorite?: boolean | null;
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishCard"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dish_api_dishes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dish_api_dishes__dish_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dish_api_dishes__dish_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_dish_api_dishes__dish_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_dish_api_dishes__dish_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_lines_api_dishes__dish_id__lines_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_dish_api_dishes__dish_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_items_api_items_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_item_api_items__item_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    amount_picker_api_items__item_id__picker_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_amount_api_items__item_id__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_item_api_items__item_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_products_api_kroger_products_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_members_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
        };
    };
    create_member_api_members_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_api_members__member_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_member_api_members__member_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_member_api_members__member_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_photo_api_photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/*": string;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"];
                };
            };
        };
    };
    get_photo_api_photos__photo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thumb_api_photos__photo_id__thumb_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_store_api_stores_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveStoreOut"];
                };
            };
        };
    };
    choose_store_api_stores_active_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChooseStore"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_stores_api_stores_search_get: {
        parameters: {
            query: {
                zip: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreOption"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
        };
    };
}
